2019-10-18 14:21:05,250 TestSqlUser FATAL - Error Code :-2146232060 - AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'.
The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.
2019-10-18 14:21:05,273 TestSqlUser2 FATAL - Errors :Message : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. Exception Number : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. Source : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. Server : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. Procedure : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. LineNumber : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'.Message : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. Exception Number : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. Source : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. Server : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. Procedure : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. LineNumber : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.
2019-10-18 14:21:05,284 TestUser FATAL - AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'.
The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.
System.Data.SqlClient.SqlException (0x80131904): AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'.
The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.AddKioskDetails(Kiosk kiosk, String user) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.Kiosk.cs:line 1145
   at EMIS.PatientFlow.Repositories.KioskRepository.AddKioskDetails(Kiosk kiosk) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\KioskRepository.cs:line 287
ClientConnectionId:c42a3e2d-30b1-43a5-a678-f37b67e6ec35
Error Number:50000,State:1,Class:16
2019-10-18 14:24:56,712 TestSqlUser FATAL - Error Code :-2146232060 - AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'.
The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.
2019-10-18 14:24:56,715 TestSqlUser2 FATAL - Errors :Message : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. Exception Number : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. Source : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. Server : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. Procedure : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'. LineNumber : AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'.Message : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. Exception Number : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. Source : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. Server : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. Procedure : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. LineNumber : The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.
2019-10-18 14:24:56,718 TestUser FATAL - AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'.
The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.
System.Data.SqlClient.SqlException (0x80131904): AddKioskDetails : 547: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientFlow_KioskLinkedToDetails_TypeId". The conflict occurred in database "EMISPatientFlowConfiguration", table "PatientFlow.Organisation", column 'OrganisationId'.
The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.AddKioskDetails(Kiosk kiosk, String user) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.Kiosk.cs:line 1145
   at EMIS.PatientFlow.Repositories.KioskRepository.AddKioskDetails(Kiosk kiosk) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\KioskRepository.cs:line 287
ClientConnectionId:c42a3e2d-30b1-43a5-a678-f37b67e6ec35
Error Number:50000,State:1,Class:16
2019-10-18 15:33:59,580 TestSqlUser FATAL - Error Code :-2146232060 - A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
2019-10-18 15:33:59,616 TestSqlUser2 FATAL - Errors :Message : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Exception Number : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Source : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Server : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Procedure : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) LineNumber : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-10-18 15:33:59,952 TestUser FATAL - Error Code :-2146232060 - A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
2019-10-18 15:34:15,549 TestSqlUser2 FATAL - A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at EMIS.PatientFlow.Common.Database.DbManager.Open(SqlConnection connection) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Common\Database\DBManager.cs:line 60
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.GetKioskDetails(Int32 kioskId) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.Kiosk.cs:line 21
   at EMIS.PatientFlow.Repositories.KioskRepository.GetKioskDetailsForSync(Int32 kioskId) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\KioskRepository.cs:line 170
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-10-18 15:34:25,869 TestSqlUser2 FATAL - Error Code :-2146232060 - A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
2019-10-18 15:34:30,423 TestSqlUser2 FATAL - Errors :Message : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Exception Number : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Source : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Server : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Procedure : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) LineNumber : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-10-18 15:34:30,425 TestUser FATAL - A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at EMIS.PatientFlow.Common.Database.DbManager.Open(SqlConnection connection) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Common\Database\DBManager.cs:line 60
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.DisconnectKiosk(String connectionId) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.Kiosk.cs:line 496
   at EMIS.PatientFlow.Repositories.KioskRepository.DisconnectKiosk(String connectionId) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\KioskRepository.cs:line 260
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-10-18 15:34:30,394 db4ae543-130b-4473-bebf-11619341c632 FATAL - Errors :Message : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Exception Number : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Source : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Server : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) Procedure : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) LineNumber : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-10-18 15:34:30,432 TestUser FATAL - A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at EMIS.PatientFlow.Common.Database.DbManager.Open(SqlConnection connection) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Common\Database\DBManager.cs:line 60
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.IsExistSyncService(Guid productKey) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.SyncService.cs:line 20
   at EMIS.PatientFlow.Repositories.SyncServiceRepository.IsExistSyncService(Guid productKey) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\SyncServiceRepository.cs:line 16
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-10-18 15:34:40,207 TestSqlUser FATAL - Error Code :-2146232060 - Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
2019-10-18 15:34:42,550 TestSqlUser2 FATAL - Error Code :-2146232060 - Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
2019-10-18 15:34:40,226 TestSqlUser2 FATAL - Error Code :-2146232060 - Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
2019-10-18 15:34:42,504 TestSqlUser2 FATAL - Error Code :-2146232060 - Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
2019-10-18 15:34:50,298 TestSqlUser2 FATAL - Errors :Message : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Exception Number : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Source : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Server : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Procedure : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. LineNumber : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.Message : Login failed for user 'EMISGROUP\Archana.Reddy'. Exception Number : Login failed for user 'EMISGROUP\Archana.Reddy'. Source : Login failed for user 'EMISGROUP\Archana.Reddy'. Server : Login failed for user 'EMISGROUP\Archana.Reddy'. Procedure : Login failed for user 'EMISGROUP\Archana.Reddy'. LineNumber : Login failed for user 'EMISGROUP\Archana.Reddy'.
2019-10-18 15:34:50,260 TestUser FATAL - Errors :Message : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Exception Number : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Source : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Server : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Procedure : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. LineNumber : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.Message : Login failed for user 'EMISGROUP\Archana.Reddy'. Exception Number : Login failed for user 'EMISGROUP\Archana.Reddy'. Source : Login failed for user 'EMISGROUP\Archana.Reddy'. Server : Login failed for user 'EMISGROUP\Archana.Reddy'. Procedure : Login failed for user 'EMISGROUP\Archana.Reddy'. LineNumber : Login failed for user 'EMISGROUP\Archana.Reddy'.
2019-10-18 15:34:50,262 TestUser FATAL - Errors :Message : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Exception Number : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Source : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Server : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Procedure : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. LineNumber : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.Message : Login failed for user 'EMISGROUP\Archana.Reddy'. Exception Number : Login failed for user 'EMISGROUP\Archana.Reddy'. Source : Login failed for user 'EMISGROUP\Archana.Reddy'. Server : Login failed for user 'EMISGROUP\Archana.Reddy'. Procedure : Login failed for user 'EMISGROUP\Archana.Reddy'. LineNumber : Login failed for user 'EMISGROUP\Archana.Reddy'.
2019-10-18 15:34:50,279 TestUser FATAL - Errors :Message : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Exception Number : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Source : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Server : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. Procedure : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed. LineNumber : Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.Message : Login failed for user 'EMISGROUP\Archana.Reddy'. Exception Number : Login failed for user 'EMISGROUP\Archana.Reddy'. Source : Login failed for user 'EMISGROUP\Archana.Reddy'. Server : Login failed for user 'EMISGROUP\Archana.Reddy'. Procedure : Login failed for user 'EMISGROUP\Archana.Reddy'. LineNumber : Login failed for user 'EMISGROUP\Archana.Reddy'.
2019-10-18 15:34:50,352 TestUser FATAL - Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at EMIS.PatientFlow.Common.Database.DbManager.Open(SqlConnection connection) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Common\Database\DBManager.cs:line 60
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.SaveSyncServiceConnection(Guid productKey, Guid connectionId, Char connectionType, Boolean isDisconnect) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.SyncService.cs:line 318
   at EMIS.PatientFlow.Repositories.SyncServiceRepository.SyncServiceDisconnected(Guid productKey, Guid connectionId, Char connectionType) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\SyncServiceRepository.cs:line 58
ClientConnectionId:b5a1905f-48c3-4165-b69d-8e473d0c871c
Error Number:4060,State:1,Class:11
2019-10-18 15:34:50,305 TestUser FATAL - Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at EMIS.PatientFlow.Common.Database.DbManager.Open(SqlConnection connection) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Common\Database\DBManager.cs:line 60
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.IsExistSyncService(Guid productKey) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.SyncService.cs:line 20
   at EMIS.PatientFlow.Repositories.SyncServiceRepository.IsExistSyncService(Guid productKey) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\SyncServiceRepository.cs:line 16
ClientConnectionId:b5a1905f-48c3-4165-b69d-8e473d0c871c
Error Number:4060,State:1,Class:11
2019-10-18 15:34:50,323 14737983-8f9a-45c7-bd31-1c107d04ab65 FATAL - Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at EMIS.PatientFlow.Common.Database.DbManager.Open(SqlConnection connection) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Common\Database\DBManager.cs:line 60
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.IsExistSyncService(Guid productKey) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.SyncService.cs:line 20
   at EMIS.PatientFlow.Repositories.SyncServiceRepository.IsExistSyncService(Guid productKey) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\SyncServiceRepository.cs:line 16
ClientConnectionId:b5a1905f-48c3-4165-b69d-8e473d0c871c
Error Number:4060,State:1,Class:11
2019-10-18 15:34:50,337 14737983-8f9a-45c7-bd31-1c107d04ab65 FATAL - Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "EMISPatientFlowConfiguration" requested by the login. The login failed.
Login failed for user 'EMISGROUP\Archana.Reddy'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at EMIS.PatientFlow.Common.Database.DbManager.Open(SqlConnection connection) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Common\Database\DBManager.cs:line 60
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.IsExistSyncService(Guid productKey) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.SyncService.cs:line 20
   at EMIS.PatientFlow.Repositories.SyncServiceRepository.IsExistSyncService(Guid productKey) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\SyncServiceRepository.cs:line 16
ClientConnectionId:b5a1905f-48c3-4165-b69d-8e473d0c871c
Error Number:4060,State:1,Class:11
2019-10-18 16:07:54,869 14737983-8f9a-45c7-bd31-1c107d04ab65 FATAL - Error Code :-2146232060 - Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=24; handshake=13; 
System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
2019-10-18 16:07:54,931 TestSqlUser2 FATAL - Errors :Message : Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=24; handshake=13;  Exception Number : Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=24; handshake=13;  Source : Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=24; handshake=13;  Server : Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=24; handshake=13;  Procedure : Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=24; handshake=13;  LineNumber : Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=24; handshake=13; 
2019-10-18 16:07:54,936 TestUser FATAL - Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=24; handshake=13; 
System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=24; handshake=13;  ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at EMIS.PatientFlow.Common.Database.DbManager.Open(SqlConnection connection) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Common\Database\DBManager.cs:line 60
   at EMIS.PatientFlow.DatabaseAccess.DbAccess.GetKioskUsageLog(List`1 KioskGuids) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.DatabaseAccess\DBAccess.Kiosk.cs:line 1696
   at EMIS.PatientFlow.Repositories.KioskRepository.GetKioskUsageLog(List`1 KioskGuids) in C:\Code\NewPortal(UIWithUX)\NewPortal\EMIS.PatientFlow\EMIS.PatientFlow.Repositories\KioskRepository.cs:line 595
ClientConnectionId:98b07808-8b99-49d3-a2cc-f801595926bb
Error Number:-2,State:0,Class:11
